package com.buychemi.crm.bean

/**
 * Updated by 20342 on 2019-10-22
 */
data class CompanyDetailsEntity(var id: Int,
                                var companyName: String?,
                                var industryId: Int,
                                var industryName: String?,
                                var type: Int?,
                                var area: String?,
                                var areaName: String?,
                                var address: String?,
                                var businessScale: String?,
                                var companyLicense: String?,
                                var businessScope: String?,
                                var mainProducts: String?,
                                var createId: String?,
                                var createTime: String?,
                                var updateTime: String?,
                                var updateId: Int,
                                var isDelete: Int,
                                var isNew: String?,
                                var customer: Customer?,
                                var contactName: String?,
                                var contactMobile: String?,
                                var registerDate: String?,
                                var companyEmail: String?,
                                var companyUrl: String?,
                                var issueDate: String?,
                                var companyWay: String?,
                                var companyScale: String?,
                                var companyDesc: String?,
                                var creditCode: String?,
                                var rating: Int,
                                var companySource: String?,
                                var customerId: String?,
                                var companyIndustry: String?,
                                var companyType: String?,
                                var companySourceName: String?,
                                var customerCount: String?,
                                var isSync: String?,
                                var companyValue: Int?) {
    data class Customer(var id: Int,
                        var companyId: Int,
                        var name: String?,
                        var tel: String?,
                        var email: String?,
                        var sex: Int,
                        var birth: String?,
                        var position: String?,
                        var invitePeople: String?,
                        var classification: String?,
                        var resource: String?,
                        var resourceName: String?,
                        var customerState: Int,
                        var evaluationStatus: Int,
                        var jobCertification: Int,
                        var isGroup: Int,
                        var inviteId: String?,
                        var userValue: Int,
                        var customerRating: String?,
                        var primaryContact: Int,
                        var remark: String?,
                        var createId: Int,
                        var createTime: String?,
                        var updateTime: String?,
                        var updateId: Int,
                        var isDelete: Int,
                        var company: String?,
                        var isMove: String?,
                        var groupId: String?,
                        var isPotential: Int,
                        var businessCard: String?,
                        var companyName: String?,
                        var customerResource: Int,
                        var customerResourceName: String?,
                        var address: String?,
                        var groupName: String?)
}