package com.buychemi.crm.bean

/**
 * Updated by 20342 on 2019-10-22
 */
data class CustomerSearchEntity(var id: Int,
                                var companyId: Int,
                                var name: String?,
                                var tel: String?,
                                var email: String,
                                var sex: Int,
                                var birth: String,
                                var position: String?,
                                var invitePeople: Any,
                                var classification: Any,
                                var resource: Any,
                                var resourceName: String,
                                var customerState: Int,
                                var evaluationStatus: Int,
                                var jobCertification: Int,
                                var isGroup: Int,
                                var inviteId: Any,
                                var userValue: Int,
                                var customerRating: Int,
                                var primaryContact: Int,
                                var remark: Any,
                                var createId: Int,
                                var createTime: String,
                                var updateTime: String,
                                var updateId: Int,
                                var isDelete: Int,
                                var company: Company,
                                var isMove: Any,
                                var groupId: Any,
                                var isPotential: Int,
                                var businessCard: String,
                                var companyName: Any,
                                var customerResource: Int,
                                var customerResourceName: Any,
                                var address: Any,
                                var groupName: Any?) {
    data class Company(var id: Int,
                       var companyName: String,
                       var industryId: Any,
                       var industryName: String,
                       var type: Int,
                       var area: Int,
                       var areaName: Any,
                       var address: String,
                       var businessScale: Any,
                       var companyLicense: String,
                       var businessScope: Any,
                       var mainProducts: Any,
                       var createId: Any,
                       var createTime: String,
                       var updateTime: Any,
                       var updateId: Any,
                       var isDelete: Any,
                       var isNew: Any,
                       var customer: Any,
                       var contactName: Any,
                       var contactMobile: Any,
                       var registerDate: Any,
                       var companyEmail: Any,
                       var companyUrl: Any,
                       var issueDate: Any,
                       var companyWay: Any,
                       var companyScale: Any,
                       var companyDesc: Any,
                       var creditCode: Any,
                       var rating: Any,
                       var companySource: Any,
                       var customerId: Any,
                       var companyIndustry: Any,
                       var companyType: Any,
                       var companySourceName: Any,
                       var customerCount: Any,
                       var isSync: Any,
                       var companyValue: Any)
}