package com.buychemi.crm.bean

/**
 * Updated by 20342 on 2019-10-18
 */
data class CustomerDetailsEntity(var id: Int,
                                 var companyId: Int,
                                 var name: String?,
                                 var tel: String?,
                                 var email: String?,
                                 var sex: Int,
                                 var birth: String?,
                                 var position: String?="",
                                 var invitePeople: String?,
                                 var classification: String?,
                                 var resource: String?,
                                 var resourceName: String?,
                                 var customerState: Int,
                                 var evaluationStatus: Int,
                                 var jobCertification: Int,
                                 var isGroup: Int,
                                 var inviteId: Int,
                                 var userValue: Int,
                                 var customerRating: String?,
                                 var primaryContact: Int,
                                 var remark: String?,
                                 var createId: Int,
                                 var createTime: String?,
                                 var updateTime: String?,
                                 var updateId: Int,
                                 var isDelete: Int,
                                 var company: Company?,
                                 var isMove: String?,
                                 var groupId: String?,
                                 var isPotential: Int,
                                 var businessCard: String?,
                                 var companyName: String?,
                                 var customerResource: String?,
                                 var customerResourceName: String?,
                                 var address: String?,
                                 var groupName: String?) {
    data class Company(var id: Int,
                       var companyName: String?,
                       var industryId: Int,
                       var industryName: String?,
                       var type: Int,
                       var area: Int,
                       var areaName: String?,
                       var address: String?,
                       var businessScale: String?,
                       var companyLicense: String?,
                       var businessScope: String?,
                       var mainProducts: String?,
                       var createId: String?,
                       var createTime: String?,
                       var updateTime: String?,
                       var updateId: String?,
                       var isDelete: Int,
                       var isNew: String?,
                       var customer: String?,
                       var contactName: String?,
                       var contactMobile: String?,
                       var registerDate: String?,
                       var companyEmail: String?,
                       var companyUrl: String?,
                       var issueDate: String?,
                       var companyWay: String?,
                       var companyScale: String?,
                       var companyDesc: String?,
                       var creditCode: String?,
                       var rating: String?,
                       var companySource: String?,
                       var customerId: String?,
                       var companyIndustry: String?,
                       var companyType: String?,
                       var companySourceName: String?,
                       var customerCount: String?,
                       var isSync: String?,
                       var companyValue: String?)
}